def Drawsquare(turtle_side ):
    import turtle
    turtle.speed(1)
    turtle.showturtle()
    turtle_side = turtle.numinput(" ", "Enter a number: ")
    turtle.forward(turtle_side)
    turtle.left(90)
    turtle.forward(turtle_side)
    turtle.left(90)
    turtle.forward(turtle_side)
    turtle.left(90)
    turtle.forward(turtle_side)
    turtle.left(90)

    turtle.left(30)
    turtle.forward(turtle_side)
    turtle.left(90)
    turtle.forward(turtle_side)
    turtle.left(90)
    turtle.forward(turtle_side)
    turtle.left(90)
    turtle.forward(turtle_side)
    turtle.left(90)

    turtle.left(30)
    turtle.forward(turtle_side)
    turtle.left(90)
    turtle.forward(turtle_side)
    turtle.left(90)
    turtle.forward(turtle_side)
    turtle.left(90)
    turtle.forward(turtle_side)
    turtle.left(90)

    turtle.left(30)
    turtle.forward(turtle_side)
    turtle.left(90)
    turtle.forward(turtle_side)
    turtle.left(90)
    turtle.forward(turtle_side)
    turtle.left(90)
    turtle.forward(turtle_side)
    turtle.left(90)

Drawsquare("turtle_side" )
